### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by Ragha2207** [Capgemini-AIE/bot-framework-actions-on-google#30]
Hi,

I tried the NodeJs solution. Included my DirectlineSecret of my Microsoft-Bot in the
var DirectlineSecret = ".................................";
app.use(actionsOnGoogleAdapter(DirectlineSecret).router);

but I am getting the following error:

TypeError: Cannot read property 'toLowerCase' of null
at continueConversation (\bot-framework-actions-on-google\lib\fulfilment.js:71:36)
at \bot-framework-actions-on-google\lib\fulfilment.js:122:5
at ActionsSdkApp.handleRequestAsync (actions-on-google\assistant-app.js:511:29)
at ActionsSdkApp.handleRequest (actions-on-google\assistant-app.js:419:10)
at bot-framework-actions-on-google\lib\fulfilment.js:135:9
at Layer.handle [as handle_request] (express\lib\router\layer.js:95:5)
at trim_prefix (\express\lib\router\index.js:317:13)
at express\lib\router\index.js:284:7
at Function.process_params \express\lib\router\index.js:335:12)
at next (express\lib\router\index.js:275:10)

Please help me with this issue.

Kind Regards,
Ragha

**Comment by vignesh-123** [comment]
I am also having the same issue. Is the module working for anyone.

**Comment by vignesh-123** [comment]
I was hitting the wrong URL. That is the reason for the issue. Once I changed that the connection established

**Comment by ghost** [comment]
@vignesh-123 What do you mean by hitting the wrong URL ? I am also facing the same issue.

**Comment by alejandroesteban** [comment]
Hello friend, could you solve your problem? which url has to be configured.
I have for example: https://domain.azurewebsites.net/api/messages

**Comment by alejandroesteban** [comment]
> @vignesh-123 What do you mean by hitting the wrong URL ? I am also facing the same issue.

Hello friend, could you solve your problem? which url has to be configured.
I have for example: https://domain.azurewebsites.net/api/messages

**Comment by alejandroesteban** [comment]
> @SiddharthSunchu What do you mean by hitting the wrong URL ? I am also facing the same issue.


Hello friend, could you solve your problem? which url has to be configured.
I have for example: https://domain.azurewebsites.net/api/messages
